import type { Metadata } from "next";
import { Instrument_Serif, Inter } from "next/font/google";
import "./globals.css";

const instrument_Serif = Instrument_Serif({
  weight: "400",
  variable: "--font-instrument-serif",
});
const inter = Inter({
  weight: "400",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "IFNOTGODTECH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrument_Serif.variable} ${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
