export const blogPosts = [
    {
        id: 1,
        image: "/images/ProgrammeratWork.png",
        title: "Building Scalable Software Architecture for Growing Businesses",
        date: "June 20, 2025",
        category: "Development",
        preview: "Learn the basics of React development and start building modern web applications.",
        readTime: "5 min read",
    },
    {
        id: 2,
        image: "/images/ProgrammeratWork.png",
        title: "UI/UX Trends to Watch in 2025",
        date: "June 18, 2025",
        category: "UI/UX Design",
        preview: "Discover the latest design trends that will shape user experiences this year.",
        readTime: "4 min read",
    },
    {
        id: 3,
        image: "/images/ProgrammeratWork.png",
        title: "Quality Assurance Best Practices",
        date: "June 15, 2025",
        category: "Quality Assurance",
        preview: "Ensure your software works flawlessly with these QA strategies.",
        readTime: "6 min read",
    },
    {
        id: 4,
        image: "/images/ProgrammeratWork.png",
        title: "Effective Project Management in Tech Teams",
        date: "June 10, 2025",
        category: "IT Consulting",
        preview: "Tips and tools for managing software projects efficiently.",
        readTime: "7 min read",
    },
    {
        id: 5,
        image: "/images/ProgrammeratWork.png",
        title: "Getting Started with Next.js",
        date: "June 8, 2025",
        category: "Development",
        preview: "A beginner’s guide to building fast web apps with Next.js.",
        readTime: "5 min read",
    },
    {
        id: 6,
        image: "/images/ProgrammeratWork.png",
        title: "Design Systems: Why Your Startup Needs One",
        date: "June 5, 2025",
        category: "UI/UX Design",
        preview: "How design systems help teams scale and stay consistent.",
        readTime: "4 min read",
    },
    {
        id: 7,
        image: "/images/ProgrammeratWork.png",
        title: "Automated Testing for Modern Web Apps",
        date: "June 2, 2025",
        category: "Quality Assurance",
        preview: "Learn how automated tests can save time and reduce bugs.",
        readTime: "6 min read",
    },
    {
        id: 8,
        image: "/images/ProgrammeratWork.png",
        title: "How to Build a Portfolio Website",
        date: "May 30, 2025",
        category: "Development",
        preview: "Showcase your work and attract clients with a great portfolio.",
        readTime: "5 min read",
    },
    {
        id: 9,
        image: "/images/ProgrammeratWork.png",
        title: "The Power of User Feedback in Product Design",
        date: "May 28, 2025",
        category: "UI/UX Design",
        preview: "Use real user feedback to improve your product’s experience.",
        readTime: "4 min read",
    },
    {
        id: 10,
        image: "/images/ProgrammeratWork.png",
        title: "Scaling Your App for Global Users",
        date: "May 25, 2025",
        category: "Development",
        preview: "Best practices for making your app ready for international audiences.",
        readTime: "7 min read",
    },
    {
        id: 11,
        image: "/images/ProgrammeratWork.png",
        title: "Agile vs. Waterfall: Choosing the Right Approach",
        date: "May 22, 2025",
        category: "IT Consulting",
        preview: "Compare agile and waterfall methodologies for your next project.",
        readTime: "6 min read",
    },
    {
        id: 12,
        image: "/images/ProgrammeratWork.png",
        title: "Optimizing Web Performance in 2025",
        date: "May 20, 2025",
        category: "Development",
        preview: "Speed matters! Learn how to make your site load faster.",
        readTime: "5 min read",
    },
];